// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"concept-tracker/internal/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockConceptRepository creates a new instance of MockConceptRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConceptRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConceptRepository {
	mock := &MockConceptRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConceptRepository is an autogenerated mock type for the ConceptRepository type
type MockConceptRepository struct {
	mock.Mock
}

type MockConceptRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConceptRepository) EXPECT() *MockConceptRepository_Expecter {
	return &MockConceptRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockConceptRepository
func (_mock *MockConceptRepository) Create(ctx context.Context, userID string, concept domain.Concept) (domain.Concept, error) {
	ret := _mock.Called(ctx, userID, concept)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Concept
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.Concept) (domain.Concept, error)); ok {
		return returnFunc(ctx, userID, concept)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.Concept) domain.Concept); ok {
		r0 = returnFunc(ctx, userID, concept)
	} else {
		r0 = ret.Get(0).(domain.Concept)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, domain.Concept) error); ok {
		r1 = returnFunc(ctx, userID, concept)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConceptRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockConceptRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - concept domain.Concept
func (_e *MockConceptRepository_Expecter) Create(ctx interface{}, userID interface{}, concept interface{}) *MockConceptRepository_Create_Call {
	return &MockConceptRepository_Create_Call{Call: _e.mock.On("Create", ctx, userID, concept)}
}

func (_c *MockConceptRepository_Create_Call) Run(run func(ctx context.Context, userID string, concept domain.Concept)) *MockConceptRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.Concept
		if args[2] != nil {
			arg2 = args[2].(domain.Concept)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConceptRepository_Create_Call) Return(concept1 domain.Concept, err error) *MockConceptRepository_Create_Call {
	_c.Call.Return(concept1, err)
	return _c
}

func (_c *MockConceptRepository_Create_Call) RunAndReturn(run func(ctx context.Context, userID string, concept domain.Concept) (domain.Concept, error)) *MockConceptRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockConceptRepository
func (_mock *MockConceptRepository) Delete(ctx context.Context, userID string, id string) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConceptRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockConceptRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *MockConceptRepository_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}) *MockConceptRepository_Delete_Call {
	return &MockConceptRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *MockConceptRepository_Delete_Call) Run(run func(ctx context.Context, userID string, id string)) *MockConceptRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConceptRepository_Delete_Call) Return(err error) *MockConceptRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConceptRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, userID string, id string) error) *MockConceptRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockConceptRepository
func (_mock *MockConceptRepository) GetByID(ctx context.Context, userID string, id string) (domain.Concept, error) {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Concept
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (domain.Concept, error)); ok {
		return returnFunc(ctx, userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) domain.Concept); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Get(0).(domain.Concept)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConceptRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockConceptRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *MockConceptRepository_Expecter) GetByID(ctx interface{}, userID interface{}, id interface{}) *MockConceptRepository_GetByID_Call {
	return &MockConceptRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, id)}
}

func (_c *MockConceptRepository_GetByID_Call) Run(run func(ctx context.Context, userID string, id string)) *MockConceptRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConceptRepository_GetByID_Call) Return(concept domain.Concept, err error) *MockConceptRepository_GetByID_Call {
	_c.Call.Return(concept, err)
	return _c
}

func (_c *MockConceptRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, userID string, id string) (domain.Concept, error)) *MockConceptRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetChildren provides a mock function for the type MockConceptRepository
func (_mock *MockConceptRepository) GetChildren(ctx context.Context, userID string, id string) ([]domain.Concept, error) {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetChildren")
	}

	var r0 []domain.Concept
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]domain.Concept, error)); ok {
		return returnFunc(ctx, userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []domain.Concept); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Concept)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConceptRepository_GetChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChildren'
type MockConceptRepository_GetChildren_Call struct {
	*mock.Call
}

// GetChildren is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *MockConceptRepository_Expecter) GetChildren(ctx interface{}, userID interface{}, id interface{}) *MockConceptRepository_GetChildren_Call {
	return &MockConceptRepository_GetChildren_Call{Call: _e.mock.On("GetChildren", ctx, userID, id)}
}

func (_c *MockConceptRepository_GetChildren_Call) Run(run func(ctx context.Context, userID string, id string)) *MockConceptRepository_GetChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConceptRepository_GetChildren_Call) Return(concepts []domain.Concept, err error) *MockConceptRepository_GetChildren_Call {
	_c.Call.Return(concepts, err)
	return _c
}

func (_c *MockConceptRepository_GetChildren_Call) RunAndReturn(run func(ctx context.Context, userID string, id string) ([]domain.Concept, error)) *MockConceptRepository_GetChildren_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubtree provides a mock function for the type MockConceptRepository
func (_mock *MockConceptRepository) GetSubtree(ctx context.Context, userID string, id string) ([]domain.Concept, error) {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSubtree")
	}

	var r0 []domain.Concept
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]domain.Concept, error)); ok {
		return returnFunc(ctx, userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []domain.Concept); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Concept)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConceptRepository_GetSubtree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubtree'
type MockConceptRepository_GetSubtree_Call struct {
	*mock.Call
}

// GetSubtree is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *MockConceptRepository_Expecter) GetSubtree(ctx interface{}, userID interface{}, id interface{}) *MockConceptRepository_GetSubtree_Call {
	return &MockConceptRepository_GetSubtree_Call{Call: _e.mock.On("GetSubtree", ctx, userID, id)}
}

func (_c *MockConceptRepository_GetSubtree_Call) Run(run func(ctx context.Context, userID string, id string)) *MockConceptRepository_GetSubtree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConceptRepository_GetSubtree_Call) Return(concepts []domain.Concept, err error) *MockConceptRepository_GetSubtree_Call {
	_c.Call.Return(concepts, err)
	return _c
}

func (_c *MockConceptRepository_GetSubtree_Call) RunAndReturn(run func(ctx context.Context, userID string, id string) ([]domain.Concept, error)) *MockConceptRepository_GetSubtree_Call {
	_c.Call.Return(run)
	return _c
}

// ListRoots provides a mock function for the type MockConceptRepository
func (_mock *MockConceptRepository) ListRoots(ctx context.Context, userID string) ([]domain.Concept, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListRoots")
	}

	var r0 []domain.Concept
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.Concept, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.Concept); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Concept)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConceptRepository_ListRoots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRoots'
type MockConceptRepository_ListRoots_Call struct {
	*mock.Call
}

// ListRoots is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockConceptRepository_Expecter) ListRoots(ctx interface{}, userID interface{}) *MockConceptRepository_ListRoots_Call {
	return &MockConceptRepository_ListRoots_Call{Call: _e.mock.On("ListRoots", ctx, userID)}
}

func (_c *MockConceptRepository_ListRoots_Call) Run(run func(ctx context.Context, userID string)) *MockConceptRepository_ListRoots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConceptRepository_ListRoots_Call) Return(concepts []domain.Concept, err error) *MockConceptRepository_ListRoots_Call {
	_c.Call.Return(concepts, err)
	return _c
}

func (_c *MockConceptRepository_ListRoots_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]domain.Concept, error)) *MockConceptRepository_ListRoots_Call {
	_c.Call.Return(run)
	return _c
}

// Move provides a mock function for the type MockConceptRepository
func (_mock *MockConceptRepository) Move(ctx context.Context, userID string, id string, newParentID *string) error {
	ret := _mock.Called(ctx, userID, id, newParentID)

	if len(ret) == 0 {
		panic("no return value specified for Move")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *string) error); ok {
		r0 = returnFunc(ctx, userID, id, newParentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConceptRepository_Move_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Move'
type MockConceptRepository_Move_Call struct {
	*mock.Call
}

// Move is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
//   - newParentID *string
func (_e *MockConceptRepository_Expecter) Move(ctx interface{}, userID interface{}, id interface{}, newParentID interface{}) *MockConceptRepository_Move_Call {
	return &MockConceptRepository_Move_Call{Call: _e.mock.On("Move", ctx, userID, id, newParentID)}
}

func (_c *MockConceptRepository_Move_Call) Run(run func(ctx context.Context, userID string, id string, newParentID *string)) *MockConceptRepository_Move_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockConceptRepository_Move_Call) Return(err error) *MockConceptRepository_Move_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConceptRepository_Move_Call) RunAndReturn(run func(ctx context.Context, userID string, id string, newParentID *string) error) *MockConceptRepository_Move_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockConceptRepository
func (_mock *MockConceptRepository) Update(ctx context.Context, userID string, id string, name string, description *string) (domain.Concept, error) {
	ret := _mock.Called(ctx, userID, id, name, description)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Concept
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *string) (domain.Concept, error)); ok {
		return returnFunc(ctx, userID, id, name, description)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *string) domain.Concept); ok {
		r0 = returnFunc(ctx, userID, id, name, description)
	} else {
		r0 = ret.Get(0).(domain.Concept)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, *string) error); ok {
		r1 = returnFunc(ctx, userID, id, name, description)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConceptRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockConceptRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
//   - name string
//   - description *string
func (_e *MockConceptRepository_Expecter) Update(ctx interface{}, userID interface{}, id interface{}, name interface{}, description interface{}) *MockConceptRepository_Update_Call {
	return &MockConceptRepository_Update_Call{Call: _e.mock.On("Update", ctx, userID, id, name, description)}
}

func (_c *MockConceptRepository_Update_Call) Run(run func(ctx context.Context, userID string, id string, name string, description *string)) *MockConceptRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *string
		if args[4] != nil {
			arg4 = args[4].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockConceptRepository_Update_Call) Return(concept domain.Concept, err error) *MockConceptRepository_Update_Call {
	_c.Call.Return(concept, err)
	return _c
}

func (_c *MockConceptRepository_Update_Call) RunAndReturn(run func(ctx context.Context, userID string, id string, name string, description *string) (domain.Concept, error)) *MockConceptRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
