// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"concept-tracker/internal/domain"
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockActivityLogRepository creates a new instance of MockActivityLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActivityLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActivityLogRepository {
	mock := &MockActivityLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActivityLogRepository is an autogenerated mock type for the ActivityLogRepository type
type MockActivityLogRepository struct {
	mock.Mock
}

type MockActivityLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActivityLogRepository) EXPECT() *MockActivityLogRepository_Expecter {
	return &MockActivityLogRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockActivityLogRepository
func (_mock *MockActivityLogRepository) Create(ctx context.Context, userID string, conceptID string, activity domain.ActivityLog) (domain.ActivityLog, error) {
	ret := _mock.Called(ctx, userID, conceptID, activity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.ActivityLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.ActivityLog) (domain.ActivityLog, error)); ok {
		return returnFunc(ctx, userID, conceptID, activity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.ActivityLog) domain.ActivityLog); ok {
		r0 = returnFunc(ctx, userID, conceptID, activity)
	} else {
		r0 = ret.Get(0).(domain.ActivityLog)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, domain.ActivityLog) error); ok {
		r1 = returnFunc(ctx, userID, conceptID, activity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityLogRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockActivityLogRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - conceptID string
//   - activity domain.ActivityLog
func (_e *MockActivityLogRepository_Expecter) Create(ctx interface{}, userID interface{}, conceptID interface{}, activity interface{}) *MockActivityLogRepository_Create_Call {
	return &MockActivityLogRepository_Create_Call{Call: _e.mock.On("Create", ctx, userID, conceptID, activity)}
}

func (_c *MockActivityLogRepository_Create_Call) Run(run func(ctx context.Context, userID string, conceptID string, activity domain.ActivityLog)) *MockActivityLogRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 domain.ActivityLog
		if args[3] != nil {
			arg3 = args[3].(domain.ActivityLog)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockActivityLogRepository_Create_Call) Return(activityLog domain.ActivityLog, err error) *MockActivityLogRepository_Create_Call {
	_c.Call.Return(activityLog, err)
	return _c
}

func (_c *MockActivityLogRepository_Create_Call) RunAndReturn(run func(ctx context.Context, userID string, conceptID string, activity domain.ActivityLog) (domain.ActivityLog, error)) *MockActivityLogRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockActivityLogRepository
func (_mock *MockActivityLogRepository) Delete(ctx context.Context, userID string, id string) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActivityLogRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockActivityLogRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *MockActivityLogRepository_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}) *MockActivityLogRepository_Delete_Call {
	return &MockActivityLogRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *MockActivityLogRepository_Delete_Call) Run(run func(ctx context.Context, userID string, id string)) *MockActivityLogRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockActivityLogRepository_Delete_Call) Return(err error) *MockActivityLogRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActivityLogRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, userID string, id string) error) *MockActivityLogRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockActivityLogRepository
func (_mock *MockActivityLogRepository) List(ctx context.Context, userID string, conceptID string, cursor *domain.Cursor, limit int) ([]domain.ActivityLog, error) {
	ret := _mock.Called(ctx, userID, conceptID, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.ActivityLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *domain.Cursor, int) ([]domain.ActivityLog, error)); ok {
		return returnFunc(ctx, userID, conceptID, cursor, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *domain.Cursor, int) []domain.ActivityLog); ok {
		r0 = returnFunc(ctx, userID, conceptID, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ActivityLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *domain.Cursor, int) error); ok {
		r1 = returnFunc(ctx, userID, conceptID, cursor, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityLogRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockActivityLogRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - conceptID string
//   - cursor *domain.Cursor
//   - limit int
func (_e *MockActivityLogRepository_Expecter) List(ctx interface{}, userID interface{}, conceptID interface{}, cursor interface{}, limit interface{}) *MockActivityLogRepository_List_Call {
	return &MockActivityLogRepository_List_Call{Call: _e.mock.On("List", ctx, userID, conceptID, cursor, limit)}
}

func (_c *MockActivityLogRepository_List_Call) Run(run func(ctx context.Context, userID string, conceptID string, cursor *domain.Cursor, limit int)) *MockActivityLogRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *domain.Cursor
		if args[3] != nil {
			arg3 = args[3].(*domain.Cursor)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockActivityLogRepository_List_Call) Return(activityLogs []domain.ActivityLog, err error) *MockActivityLogRepository_List_Call {
	_c.Call.Return(activityLogs, err)
	return _c
}

func (_c *MockActivityLogRepository_List_Call) RunAndReturn(run func(ctx context.Context, userID string, conceptID string, cursor *domain.Cursor, limit int) ([]domain.ActivityLog, error)) *MockActivityLogRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockActivityLogRepository
func (_mock *MockActivityLogRepository) Update(ctx context.Context, userID string, id string, actType *string, duration *int64, notes *string, loggedAt *time.Time) (domain.ActivityLog, error) {
	ret := _mock.Called(ctx, userID, id, actType, duration, notes, loggedAt)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.ActivityLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *string, *int64, *string, *time.Time) (domain.ActivityLog, error)); ok {
		return returnFunc(ctx, userID, id, actType, duration, notes, loggedAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *string, *int64, *string, *time.Time) domain.ActivityLog); ok {
		r0 = returnFunc(ctx, userID, id, actType, duration, notes, loggedAt)
	} else {
		r0 = ret.Get(0).(domain.ActivityLog)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *string, *int64, *string, *time.Time) error); ok {
		r1 = returnFunc(ctx, userID, id, actType, duration, notes, loggedAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityLogRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockActivityLogRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
//   - actType *string
//   - duration *int64
//   - notes *string
//   - loggedAt *time.Time
func (_e *MockActivityLogRepository_Expecter) Update(ctx interface{}, userID interface{}, id interface{}, actType interface{}, duration interface{}, notes interface{}, loggedAt interface{}) *MockActivityLogRepository_Update_Call {
	return &MockActivityLogRepository_Update_Call{Call: _e.mock.On("Update", ctx, userID, id, actType, duration, notes, loggedAt)}
}

func (_c *MockActivityLogRepository_Update_Call) Run(run func(ctx context.Context, userID string, id string, actType *string, duration *int64, notes *string, loggedAt *time.Time)) *MockActivityLogRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		var arg4 *int64
		if args[4] != nil {
			arg4 = args[4].(*int64)
		}
		var arg5 *string
		if args[5] != nil {
			arg5 = args[5].(*string)
		}
		var arg6 *time.Time
		if args[6] != nil {
			arg6 = args[6].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockActivityLogRepository_Update_Call) Return(activityLog domain.ActivityLog, err error) *MockActivityLogRepository_Update_Call {
	_c.Call.Return(activityLog, err)
	return _c
}

func (_c *MockActivityLogRepository_Update_Call) RunAndReturn(run func(ctx context.Context, userID string, id string, actType *string, duration *int64, notes *string, loggedAt *time.Time) (domain.ActivityLog, error)) *MockActivityLogRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
