// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"concept-tracker/internal/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserPreferencesRepository creates a new instance of MockUserPreferencesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserPreferencesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserPreferencesRepository {
	mock := &MockUserPreferencesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserPreferencesRepository is an autogenerated mock type for the UserPreferencesRepository type
type MockUserPreferencesRepository struct {
	mock.Mock
}

type MockUserPreferencesRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserPreferencesRepository) EXPECT() *MockUserPreferencesRepository_Expecter {
	return &MockUserPreferencesRepository_Expecter{mock: &_m.Mock}
}

// GetUserPreferences provides a mock function for the type MockUserPreferencesRepository
func (_mock *MockUserPreferencesRepository) GetUserPreferences(ctx context.Context, userID string) (domain.UserPreferences, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPreferences")
	}

	var r0 domain.UserPreferences
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.UserPreferences, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.UserPreferences); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.UserPreferences)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserPreferencesRepository_GetUserPreferences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPreferences'
type MockUserPreferencesRepository_GetUserPreferences_Call struct {
	*mock.Call
}

// GetUserPreferences is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserPreferencesRepository_Expecter) GetUserPreferences(ctx interface{}, userID interface{}) *MockUserPreferencesRepository_GetUserPreferences_Call {
	return &MockUserPreferencesRepository_GetUserPreferences_Call{Call: _e.mock.On("GetUserPreferences", ctx, userID)}
}

func (_c *MockUserPreferencesRepository_GetUserPreferences_Call) Run(run func(ctx context.Context, userID string)) *MockUserPreferencesRepository_GetUserPreferences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserPreferencesRepository_GetUserPreferences_Call) Return(userPreferences domain.UserPreferences, err error) *MockUserPreferencesRepository_GetUserPreferences_Call {
	_c.Call.Return(userPreferences, err)
	return _c
}

func (_c *MockUserPreferencesRepository_GetUserPreferences_Call) RunAndReturn(run func(ctx context.Context, userID string) (domain.UserPreferences, error)) *MockUserPreferencesRepository_GetUserPreferences_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUserPreferencesRepository
func (_mock *MockUserPreferencesRepository) Update(ctx context.Context, userID string, timezone string) (domain.UserPreferences, error) {
	ret := _mock.Called(ctx, userID, timezone)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.UserPreferences
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (domain.UserPreferences, error)); ok {
		return returnFunc(ctx, userID, timezone)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) domain.UserPreferences); ok {
		r0 = returnFunc(ctx, userID, timezone)
	} else {
		r0 = ret.Get(0).(domain.UserPreferences)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, timezone)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserPreferencesRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserPreferencesRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - timezone string
func (_e *MockUserPreferencesRepository_Expecter) Update(ctx interface{}, userID interface{}, timezone interface{}) *MockUserPreferencesRepository_Update_Call {
	return &MockUserPreferencesRepository_Update_Call{Call: _e.mock.On("Update", ctx, userID, timezone)}
}

func (_c *MockUserPreferencesRepository_Update_Call) Run(run func(ctx context.Context, userID string, timezone string)) *MockUserPreferencesRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserPreferencesRepository_Update_Call) Return(userPreferences domain.UserPreferences, err error) *MockUserPreferencesRepository_Update_Call {
	_c.Call.Return(userPreferences, err)
	return _c
}

func (_c *MockUserPreferencesRepository_Update_Call) RunAndReturn(run func(ctx context.Context, userID string, timezone string) (domain.UserPreferences, error)) *MockUserPreferencesRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
