// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"concept-tracker/internal/domain"
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockActivityLogService creates a new instance of MockActivityLogService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActivityLogService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActivityLogService {
	mock := &MockActivityLogService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActivityLogService is an autogenerated mock type for the ActivityLogService type
type MockActivityLogService struct {
	mock.Mock
}

type MockActivityLogService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActivityLogService) EXPECT() *MockActivityLogService_Expecter {
	return &MockActivityLogService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockActivityLogService
func (_mock *MockActivityLogService) Create(ctx context.Context, userID string, conceptID string, activity domain.ActivityLog) (domain.ActivityLog, error) {
	ret := _mock.Called(ctx, userID, conceptID, activity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.ActivityLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.ActivityLog) (domain.ActivityLog, error)); ok {
		return returnFunc(ctx, userID, conceptID, activity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, domain.ActivityLog) domain.ActivityLog); ok {
		r0 = returnFunc(ctx, userID, conceptID, activity)
	} else {
		r0 = ret.Get(0).(domain.ActivityLog)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, domain.ActivityLog) error); ok {
		r1 = returnFunc(ctx, userID, conceptID, activity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityLogService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockActivityLogService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - conceptID string
//   - activity domain.ActivityLog
func (_e *MockActivityLogService_Expecter) Create(ctx interface{}, userID interface{}, conceptID interface{}, activity interface{}) *MockActivityLogService_Create_Call {
	return &MockActivityLogService_Create_Call{Call: _e.mock.On("Create", ctx, userID, conceptID, activity)}
}

func (_c *MockActivityLogService_Create_Call) Run(run func(ctx context.Context, userID string, conceptID string, activity domain.ActivityLog)) *MockActivityLogService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 domain.ActivityLog
		if args[3] != nil {
			arg3 = args[3].(domain.ActivityLog)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockActivityLogService_Create_Call) Return(activityLog domain.ActivityLog, err error) *MockActivityLogService_Create_Call {
	_c.Call.Return(activityLog, err)
	return _c
}

func (_c *MockActivityLogService_Create_Call) RunAndReturn(run func(ctx context.Context, userID string, conceptID string, activity domain.ActivityLog) (domain.ActivityLog, error)) *MockActivityLogService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockActivityLogService
func (_mock *MockActivityLogService) Delete(ctx context.Context, userID string, id string) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActivityLogService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockActivityLogService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
func (_e *MockActivityLogService_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}) *MockActivityLogService_Delete_Call {
	return &MockActivityLogService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *MockActivityLogService_Delete_Call) Run(run func(ctx context.Context, userID string, id string)) *MockActivityLogService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockActivityLogService_Delete_Call) Return(err error) *MockActivityLogService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActivityLogService_Delete_Call) RunAndReturn(run func(ctx context.Context, userID string, id string) error) *MockActivityLogService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockActivityLogService
func (_mock *MockActivityLogService) List(ctx context.Context, userID string, conceptID string, cursor string, limit int) (domain.ActivityLogPage, error) {
	ret := _mock.Called(ctx, userID, conceptID, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 domain.ActivityLogPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int) (domain.ActivityLogPage, error)); ok {
		return returnFunc(ctx, userID, conceptID, cursor, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int) domain.ActivityLogPage); ok {
		r0 = returnFunc(ctx, userID, conceptID, cursor, limit)
	} else {
		r0 = ret.Get(0).(domain.ActivityLogPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, int) error); ok {
		r1 = returnFunc(ctx, userID, conceptID, cursor, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityLogService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockActivityLogService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - conceptID string
//   - cursor string
//   - limit int
func (_e *MockActivityLogService_Expecter) List(ctx interface{}, userID interface{}, conceptID interface{}, cursor interface{}, limit interface{}) *MockActivityLogService_List_Call {
	return &MockActivityLogService_List_Call{Call: _e.mock.On("List", ctx, userID, conceptID, cursor, limit)}
}

func (_c *MockActivityLogService_List_Call) Run(run func(ctx context.Context, userID string, conceptID string, cursor string, limit int)) *MockActivityLogService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockActivityLogService_List_Call) Return(activityLogPage domain.ActivityLogPage, err error) *MockActivityLogService_List_Call {
	_c.Call.Return(activityLogPage, err)
	return _c
}

func (_c *MockActivityLogService_List_Call) RunAndReturn(run func(ctx context.Context, userID string, conceptID string, cursor string, limit int) (domain.ActivityLogPage, error)) *MockActivityLogService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockActivityLogService
func (_mock *MockActivityLogService) Update(ctx context.Context, userID string, id string, actType *string, duration *int64, notes *string, loggedAt *time.Time) (domain.ActivityLog, error) {
	ret := _mock.Called(ctx, userID, id, actType, duration, notes, loggedAt)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.ActivityLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *string, *int64, *string, *time.Time) (domain.ActivityLog, error)); ok {
		return returnFunc(ctx, userID, id, actType, duration, notes, loggedAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *string, *int64, *string, *time.Time) domain.ActivityLog); ok {
		r0 = returnFunc(ctx, userID, id, actType, duration, notes, loggedAt)
	} else {
		r0 = ret.Get(0).(domain.ActivityLog)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *string, *int64, *string, *time.Time) error); ok {
		r1 = returnFunc(ctx, userID, id, actType, duration, notes, loggedAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityLogService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockActivityLogService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - id string
//   - actType *string
//   - duration *int64
//   - notes *string
//   - loggedAt *time.Time
func (_e *MockActivityLogService_Expecter) Update(ctx interface{}, userID interface{}, id interface{}, actType interface{}, duration interface{}, notes interface{}, loggedAt interface{}) *MockActivityLogService_Update_Call {
	return &MockActivityLogService_Update_Call{Call: _e.mock.On("Update", ctx, userID, id, actType, duration, notes, loggedAt)}
}

func (_c *MockActivityLogService_Update_Call) Run(run func(ctx context.Context, userID string, id string, actType *string, duration *int64, notes *string, loggedAt *time.Time)) *MockActivityLogService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		var arg4 *int64
		if args[4] != nil {
			arg4 = args[4].(*int64)
		}
		var arg5 *string
		if args[5] != nil {
			arg5 = args[5].(*string)
		}
		var arg6 *time.Time
		if args[6] != nil {
			arg6 = args[6].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockActivityLogService_Update_Call) Return(activityLog domain.ActivityLog, err error) *MockActivityLogService_Update_Call {
	_c.Call.Return(activityLog, err)
	return _c
}

func (_c *MockActivityLogService_Update_Call) RunAndReturn(run func(ctx context.Context, userID string, id string, actType *string, duration *int64, notes *string, loggedAt *time.Time) (domain.ActivityLog, error)) *MockActivityLogService_Update_Call {
	_c.Call.Return(run)
	return _c
}
